# Generated by Django 5.0.8 on 2024-08-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort',), 'verbose_name_plural': 'Categories'},
        ),
    ]
