# Generated by Django 5.0.8 on 2024-08-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('sort',), 'verbose_name_plural': 'Dishes'},
        ),
    ]
